<a href="https://colab.research.google.com/github/Utsav248/Utsav_Jarga_Magar_2408957_AIML/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TO-DO-Task


## 4.1 Exercise on Functions

### Task 1

In [55]:
def convert_units():
    """
    A program that converts between different units of measurement.
    Supports length (m/ft), weight (kg/lbs), and volume (L/gal) conversions.
    Handles invalid input and conversion types.
    """

    conversion_types = {
        '1': 'Length',
        '2': 'Weight',
        '3': 'Volume'
    }

    length_conversions = {
        '1': ('meters', 'feet', 3.28084),
        '2': ('feet', 'meters', 0.3048)
    }

    weight_conversions = {
        '1': ('kilograms', 'pounds', 2.20462),
        '2': ('pounds', 'kilograms', 0.453592)
    }

    volume_conversions = {
        '1': ('liters', 'gallons', 0.264172),
        '2': ('gallons', 'liters', 3.78541)
    }

    def get_conversion_choice(options, conversion_name):
        """
        Prompts the user to choose a specific conversion within a category.
        Args:
            options (dict): A dictionary of conversion options.
            conversion_name (str): The name of the conversion category (e.g., 'Length').
        Returns:
            str: The user's valid choice.
        """
        print(f"\nChoose {conversion_name} conversion:")
        for key, (from_unit, to_unit, _) in options.items():
            print(f"{key}. Convert {from_unit} to {to_unit}")

        while True:
            choice = input(f"Enter your choice (1-{len(options)}): ")
            if choice in options:
                return choice
            else:
                print("Invalid choice. Please enter a number from the options.")

    def perform_conversion(value, from_unit, to_unit, factor):
        """
        Performs the unit conversion.
        Args:
            value (float): The value to be converted.
            from_unit (str): The unit being converted from.
            to_unit (str): The unit being converted to.
            factor (float): The conversion factor.
        Returns:
            float: The converted value.
        """
        result = value * factor
        print(f"{value} {from_unit} is equal to {result:.2f} {to_unit}")
        return result

    print("Welcome to the Unit Converter!")

    while True:
        print("\nSelect a conversion type:")
        for key, value in conversion_types.items():
            print(f"{key}. {value}")
        print("0. Exit")

        type_choice = input("Enter your choice (1-3, or 0 to exit): ")

        if type_choice == '0':
            print("Exiting Unit Converter. Goodbye!")
            break

        if type_choice not in conversion_types:
            print("Invalid conversion type. Please choose a valid option.")
            continue

        selected_type = conversion_types[type_choice]
        conversion_options = {}
        if selected_type == 'Length':
            conversion_options = length_conversions
        elif selected_type == 'Weight':
            conversion_options = weight_conversions
        elif selected_type == 'Volume':
            conversion_options = volume_conversions

        specific_conversion_choice = get_conversion_choice(conversion_options, selected_type)
        from_unit, to_unit, factor = conversion_options[specific_conversion_choice]

        while True:
            try:
                value_str = input(f"Enter the value in {from_unit} to convert: ")
                value = float(value_str)
                perform_conversion(value, from_unit, to_unit, factor)
                break
            except ValueError:
                print("Invalid input. Please enter a numeric value.")

convert_units()

Welcome to the Unit Converter!

Select a conversion type:
1. Length
2. Weight
3. Volume
0. Exit
Enter your choice (1-3, or 0 to exit): 2

Choose Weight conversion:
1. Convert kilograms to pounds
2. Convert pounds to kilograms
Enter your choice (1-2): 1
Enter the value in kilograms to convert: 2
2.0 kilograms is equal to 4.41 pounds

Select a conversion type:
1. Length
2. Weight
3. Volume
0. Exit
Enter your choice (1-3, or 0 to exit): 0
Exiting Unit Converter. Goodbye!


### Task 2

In [56]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float or int: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The average of the numbers.

    Raises:
        ValueError: If the list of numbers is empty.
    """
    if not numbers:
        raise ValueError("Cannot calculate average of an empty list.")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float or int: The maximum number in the list.

    Raises:
        ValueError: If the list of numbers is empty.
    """
    if not numbers:
        raise ValueError("Cannot find maximum of an empty list.")
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float or int: The minimum number in the list.

    Raises:
        ValueError: If the list of numbers is empty.
    """
    if not numbers:
        raise ValueError("Cannot find minimum of an empty list.")
    return min(numbers)

def perform_math_operations():
    """
    A program that performs various mathematical operations on a list of numbers.
    Supports sum, average, maximum, and minimum operations.
    Handles invalid input and empty lists.
    """

    operations = {
        '1': ('Sum', calculate_sum),
        '2': ('Average', calculate_average),
        '3': ('Maximum', find_maximum),
        '4': ('Minimum', find_minimum)
    }

    print("Welcome to the Math Operations Program!")

    while True:
        print("\nSelect an operation:")
        for key, (name, _) in operations.items():
            print(f"{key}. {name}")
        print("0. Exit")

        choice = input("Enter your choice (1-4, or 0 to exit): ")

        if choice == '0':
            print("Exiting Math Operations Program. Goodbye!")
            break

        if choice not in operations:
            print("Invalid choice. Please select a valid option.")
            continue

        selected_operation_name, selected_function = operations[choice]

        while True:
            numbers_str = input("Enter a list of numbers separated by spaces: ")
            if not numbers_str.strip():
                print("Input cannot be empty. Please enter some numbers.")
                continue

            try:
                # Convert input string to a list of floats
                numbers = [float(x) for x in numbers_str.split()]

                if not numbers:
                    raise ValueError("The list of numbers is empty.")

                result = selected_function(numbers)
                print(f"The {selected_operation_name} of {numbers_str} is: {result}")
                break
            except ValueError as e:
                print(f"Invalid input: {e}. Please enter numeric values.")
            except Exception as e:
                print(f"An unexpected error occurred: {e}")

perform_math_operations()

Welcome to the Math Operations Program!

Select an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
0. Exit
Enter your choice (1-4, or 0 to exit): 1
Enter a list of numbers separated by spaces: 1 2 3 4 
The Sum of 1 2 3 4  is: 10.0

Select an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
0. Exit
Enter your choice (1-4, or 0 to exit): 0
Exiting Math Operations Program. Goodbye!


## 4.2 Exercise on List Manipulation

### 1. Extract Every Other Element

In [57]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element from the original list.
    """
    return lst[::2]

# Example usage:
example_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(example_list)
print(f"Original list: {example_list}")
print(f"Every other element: {result}")

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


### 2. Slice a Sublist

In [58]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from a given list, starting from a specified index
    and ending at another specified index (inclusive).

    Args:
        lst (list): The input list.
        start (int): The starting index.
        end (int): The ending index (inclusive).

    Returns:
        list: The sublist from start to end (inclusive).
    """
    return lst[start:end+1]

# Example usage:
example_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
result = get_sublist(example_list, start_index, end_index)
print(f"Original list: {example_list}")
print(f"Sublist from index {start_index} to {end_index}: {result}")

Original list: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4: [3, 4, 5]


### Task 3: Reverse a List Using Slicing

In [59]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Args:
        lst (list): The input list.

    Returns:
        list: The reversed list.
    """
    return lst[::-1]

# Example usage:
example_list = [1, 2, 3, 4, 5]
result = reverse_list(example_list)
print(f"Original list: {example_list}")
print(f"Reversed list: {result}")

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


### Task 4: Remove the First and Last Elements

In [60]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list without the first and last elements.
    """
    if len(lst) < 2:
        return [] # Returns an empty list if there are fewer than 2 elements
    return lst[1:-1]

# Example usage:
example_list = [1, 2, 3, 4, 5]
result = remove_first_last(example_list)
print(f"Original list: {example_list}")
print(f"List after removing first and last elements: {result}")

example_list_short = [1]
result_short = remove_first_last(example_list_short)
print(f"\nOriginal list (short): {example_list_short}")
print(f"List after removing first and last elements (short): {result_short}")

Original list: [1, 2, 3, 4, 5]
List after removing first and last elements: [2, 3, 4]

Original list (short): [1]
List after removing first and last elements (short): []


### Task 5: Get the First n Elements

In [61]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Args:
        lst (list): The input list.
        n (int): The number of elements to extract from the beginning.

    Returns:
        list: A new list containing the first n elements.
    """
    return lst[:n]

# Example usage:
example_list = [1, 2, 3, 4, 5]
n_value = 3
result = get_first_n(example_list, n_value)
print(f"Original list: {example_list}")
print(f"First {n_value} elements: {result}")

Original list: [1, 2, 3, 4, 5]
First 3 elements: [1, 2, 3]


### Task 6: Extract Elements from the End

In [62]:
def get_last_n(lst, n):
    """
    Extracts the last n elements of a list using slicing.

    Args:
        lst (list): The input list.
        n (int): The number of elements to extract from the end.

    Returns:
        list: A new list containing the last n elements.
    """
    return lst[-n:]

# Example usage:
example_list = [1, 2, 3, 4, 5]
n_value = 2
result = get_last_n(example_list, n_value)
print(f"Original list: {example_list}")
print(f"Last {n_value} elements: {result}")

Original list: [1, 2, 3, 4, 5]
Last 2 elements: [4, 5]


### Task 7: Extract Elements in Reverse Order

In [63]:
def reverse_skip(lst):
    """
    Extracts elements in reverse order starting from the second-to-last
    element and skipping one element in between.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list containing every second element starting from
              the second-to-last, moving backward.
    """
    # Start from the second-to-last element (index -2),
    # go to the beginning (index None),
    # with a step of -2.
    return lst[-2::-2]

# Example usage:
example_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(example_list)
print(f"Original list: {example_list}")
print(f"Elements in reverse order, skipping one: {result}")

Original list: [1, 2, 3, 4, 5, 6]
Elements in reverse order, skipping one: [5, 3, 1]


## 4.3 Exercise on Nested List

### Task 1: Flatten a Nested List

In [64]:
def flatten(lst):
    """
    Takes a nested list and flattens it into a single list.

    Args:
        lst (list): The nested list.

    Returns:
        list: A flattened version of the list.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item)) # Recursively flatten sublists
        else:
            flat_list.append(item)
    return flat_list

# Example usage:
example_list = [[1, 2], [3, 4], [5]]
result = flatten(example_list)
print(f"Original nested list: {example_list}")
print(f"Flattened list: {result}")

example_list_deep = [[1, 2], [3, [4, 5]], 6]
result_deep = flatten(example_list_deep)
print(f"\nOriginal deeply nested list: {example_list_deep}")
print(f"Flattened deeply nested list: {result_deep}")

Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]

Original deeply nested list: [[1, 2], [3, [4, 5]], 6]
Flattened deeply nested list: [1, 2, 3, 4, 5, 6]


### Task 2: Accessing Nested List Elements

In [65]:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Args:
        lst (list): The nested list.
        indices (list): A list of integers representing the path to the element.

    Returns:
        Any: The element at the specified position.

    Raises:
        IndexError: If any index is out of bounds.
        TypeError: If an intermediate element is not a list when more indices are provided.
    """
    current_element = lst
    for i, index in enumerate(indices):
        if not isinstance(current_element, list):
            raise TypeError(f"Element at path up to index {indices[:i]} is not a list.")
        if index < 0 or index >= len(current_element):
            raise IndexError(f"Index {index} is out of bounds for list of size {len(current_element)} at path {indices[:i]}.")
        current_element = current_element[index]
    return current_element

# Example usage:
example_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(example_list, indices)
print(f"Original nested list: {example_list}")
print(f"Indices to access: {indices}")
print(f"Element at {indices}: {result}")

# Example with deeper nesting
deep_list = [1, [2, [3, 4]], 5]
deep_indices = [1, 1, 0]
deep_result = access_nested_element(deep_list, deep_indices)
print(f"\nOriginal deeply nested list: {deep_list}")
print(f"Indices to access: {deep_indices}")
print(f"Element at {deep_indices}: {deep_result}")

# Example with invalid index
try:
    access_nested_element(example_list, [0, 5])
except (IndexError, TypeError) as e:
    print(f"\nError accessing element: {e}")

# Example with invalid type
try:
    access_nested_element(deep_list, [0, 1])
except (IndexError, TypeError) as e:
    print(f"\nError accessing element: {e}")

Original nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Indices to access: [1, 2]
Element at [1, 2]: 6

Original deeply nested list: [1, [2, [3, 4]], 5]
Indices to access: [1, 1, 0]
Element at [1, 1, 0]: 3

Error accessing element: Index 5 is out of bounds for list of size 3 at path [0].

Error accessing element: Element at path up to index [0] is not a list.


### Task 3: Sum of All Elements in a Nested List

In [66]:
def sum_nested(lst):
    """
    Calculates the sum of all the numbers in a nested list (regardless of depth).

    Args:
        lst (list): The nested list.

    Returns:
        int or float: The sum of all numeric elements in the list.
    """
    total_sum = 0
    for item in lst:
        if isinstance(item, list):
            total_sum += sum_nested(item)  # Recursively sum sublists
        elif isinstance(item, (int, float)):
            total_sum += item
    return total_sum

# Example usage:
example_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(example_list)
print(f"Original nested list: {example_list}")
print(f"Sum of all elements: {result}")

example_list_2 = [1, [2, [3, [4]]], 5]
result_2 = sum_nested(example_list_2)
print(f"\nOriginal deeply nested list 2: {example_list_2}")
print(f"Sum of all elements 2: {result_2}")

Original nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21

Original deeply nested list 2: [1, [2, [3, [4]]], 5]
Sum of all elements 2: 15


### Task 4: Remove Specific Element from a Nested List

In [67]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Args:
        lst (list): The nested list.
        elem (Any): The element to be removed.

    Returns:
        list: The modified list with all occurrences of elem removed.
    """
    modified_list = []
    for item in lst:
        if isinstance(item, list):
            # Recursively call remove_element for sublists
            modified_list.append(remove_element(item, elem))
        elif item != elem:
            modified_list.append(item)
    return modified_list

# Example usage:
example_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(example_list, element_to_remove)
print(f"Original nested list: {example_list}")
print(f"Element to remove: {element_to_remove}")
print(f"List after removing {element_to_remove}: {result}")

example_list_deep = [1, [2, [3, 2, 4]], 5, 2]
element_to_remove_deep = 2
result_deep = remove_element(example_list_deep, element_to_remove_deep)
print(f"\nOriginal deeply nested list: {example_list_deep}")
print(f"Element to remove: {element_to_remove_deep}")
print(f"List after removing {element_to_remove_deep}: {result_deep}")

Original nested list: [[1, 2], [3, 2], [4, 5]]
Element to remove: 2
List after removing 2: [[1], [3], [4, 5]]

Original deeply nested list: [1, [2, [3, 2, 4]], 5, 2]
Element to remove: 2
List after removing 2: [1, [[3, 4]], 5]


### Task 5: Find the Maximum Element in a Nested List

In [68]:
def find_max(lst):
    """
    Finds the maximum element in a nested list (regardless of depth).

    Args:
        lst (list): The nested list.

    Returns:
        int or float: The maximum element.
    """
    max_val = float('-inf') # Initialize with negative infinity
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item)) # Recursively find max in sublists
        elif isinstance(item, (int, float)):
            max_val = max(max_val, item)
    return max_val

# Example usage:
example_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(example_list)
print(f"Original nested list: {example_list}")
print(f"Maximum element: {result}")

example_list_2 = [1, [2, [3, [10]]], 5]
result_2 = find_max(example_list_2)
print(f"\nOriginal deeply nested list 2: {example_list_2}")
print(f"Maximum element 2: {result_2}")

Original nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6

Original deeply nested list 2: [1, [2, [3, [10]]], 5]
Maximum element 2: 10


### Task 6: Count Occurrences of an Element in a Nested List

In [69]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Args:
        lst (list): The nested list.
        elem (Any): The element to count.

    Returns:
        int: The number of occurrences of the element.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count in sublists
        elif item == elem:
            count += 1
    return count

# Example usage:
example_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(example_list, element_to_count)
print(f"Original nested list: {example_list}")
print(f"Element to count: {element_to_count}")
print(f"Number of occurrences: {result}")

example_list_deep = [1, [2, [3, 2, 4]], 5, 2, 2]
element_to_count_deep = 2
result_deep = count_occurrences(example_list_deep, element_to_count_deep)
print(f"\nOriginal deeply nested list: {example_list_deep}")
print(f"Element to count: {element_to_count_deep}")
print(f"Number of occurrences: {result_deep}")

Original nested list: [[1, 2], [2, 3], [2, 4]]
Element to count: 2
Number of occurrences: 3

Original deeply nested list: [1, [2, [3, 2, 4]], 5, 2, 2]
Element to count: 2
Number of occurrences: 4


### Task 7: Flatten a List of Lists of Lists

In [70]:
def deep_flatten(lst):
    """
    Flattens a list of lists of lists into a single list, regardless of the depth.

    Args:
        lst (list): The deeply nested list.

    Returns:
        list: A single flattened list.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item)) # Recursively flatten sublists
        else:
            flat_list.append(item)
    return flat_list

# Example usage:
example_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(example_list)
print(f"Original deeply nested list: {example_list}")
print(f"Flattened list: {result}")

example_list_2 = [1, [2, [3, [4]]], 5, [[[6]]]]
result_2 = deep_flatten(example_list_2)
print(f"\nOriginal deeply nested list 2: {example_list_2}")
print(f"Flattened list 2: {result_2}")

Original deeply nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]

Original deeply nested list 2: [1, [2, [3, [4]]], 5, [[[6]]]]
Flattened list 2: [1, 2, 3, 4, 5, 6]


### Task 8: Nested List Average

In [71]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Args:
        lst (list): The nested list.

    Returns:
        float: The average of all numeric elements in the list.

    Raises:
        ValueError: If the nested list contains no numeric elements to average.
    """
    total_sum = 0
    count = 0

    def get_sum_and_count(current_list):
        nonlocal total_sum, count
        for item in current_list:
            if isinstance(item, list):
                get_sum_and_count(item) # Recursively process sublists
            elif isinstance(item, (int, float)):
                total_sum += item
                count += 1

    get_sum_and_count(lst)

    if count == 0:
        raise ValueError("Cannot calculate average of an empty or non-numeric nested list.")

    return total_sum / count

# Example usage:
example_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(example_list)
print(f"Original nested list: {example_list}")
print(f"Average of all elements: {result}")

example_list_deep = [1, [2, [3, [4]]], 5, [[[6]]]]
result_deep = average_nested(example_list_deep)
print(f"\nOriginal deeply nested list 2: {example_list_deep}")
print(f"Average of all elements 2: {result_deep}")

# Example with no numeric elements
try:
    average_nested([['a'], ['b']])
except ValueError as e:
    print(f"\nError: {e}")

Original nested list: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5

Original deeply nested list 2: [1, [2, [3, [4]]], 5, [[[6]]]]
Average of all elements 2: 3.5

Error: Cannot calculate average of an empty or non-numeric nested list.


# 10 To - Do - NumPy

## 10.1 Basic Vector and Matrix Operation with NumPy

### Problem - 1: Array Creation

#### Task 1: Initialize an empty array with size 2x2.

In [72]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:")
print(empty_array)

1. Empty 2x2 array:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


#### Task 2: Initialize an all one array with size 4x2.

In [73]:
# 2. Initialize an all one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All-ones 4x2 array:")
print(ones_array)


2. All-ones 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#### Task 3: Return a new array of given shape and type, filled with fill value. (Hint: `np.full`)

In [74]:
# 3. Return a new array of given shape and type, filled with fill value
full_array = np.full((3, 3), 7)
print("\n3. 3x3 array filled with 7:")
print(full_array)


3. 3x3 array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


#### Task 4: Return a new array of zeros with same shape and type as a given array. (Hint: `np.zeros_like`)

In [75]:
# 4. Return a new array of zeros with same shape and type as a given array
zeros_like_array = np.zeros_like(full_array)
print("\n4. Zeros array with same shape as full_array:")
print(zeros_like_array)


4. Zeros array with same shape as full_array:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Task 5: Return a new array of ones with same shape and type as a given array. (Hint: `np.ones_like`)

In [76]:
# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(empty_array)
print("\n5. Ones array with same shape as empty_array:")
print(ones_like_array)


5. Ones array with same shape as empty_array:
[[1. 1.]
 [1. 1.]]


#### Task 6: For an existing list `new_list = [1,2,3,4]` convert to a NumPy array. (Hint: `np.array()`)

In [77]:
# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array
new_list = [1, 2, 3, 4]
numpy_from_list = np.array(new_list)
print("\n6. NumPy array from list:")
print(numpy_from_list)
print(f"Type of numpy_from_list: {type(numpy_from_list)}")


6. NumPy array from list:
[1 2 3 4]
Type of numpy_from_list: <class 'numpy.ndarray'>


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing

#### Task 1: Create an array with values ranging from 10 to 49. {Hint: `np.arange()`}

In [78]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50) # np.arange excludes the stop value
print("1. Array with values from 10 to 49:")
print(array_range)

1. Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Task 2: Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for `np.reshape()`}

In [79]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix with values from 0 to 8:")
print(matrix_0_to_8)


2. 3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Task 3: Create a 3X3 identity matrix. {Hint: `np.eye()`}

In [80]:
import numpy as np

# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity matrix:")
print(identity_matrix)


3. 3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Task 4: Create a random array of size 30 and find the mean of the array. {Hint:check for `np.random.random()` and `array.mean()` function}

In [81]:
import numpy as np

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_of_random_array = random_array.mean()
print("\n4. Random array of size 30:")
print(random_array)
print(f"Mean of the random array: {mean_of_random_array:.4f}")


4. Random array of size 30:
[2.30274733e-01 8.29957899e-01 1.71932597e-01 1.47705304e-01
 8.59191252e-01 9.80431335e-01 5.05479935e-01 9.80252783e-01
 2.75965934e-01 2.11994181e-01 1.46096502e-01 5.48666747e-02
 6.03167562e-01 3.07820083e-01 6.11137090e-04 8.67587353e-01
 2.14234638e-01 3.18933031e-01 8.51672546e-01 3.57793487e-01
 7.42447432e-01 6.23808832e-01 4.82951088e-01 1.89819802e-01
 6.95907285e-01 5.09279154e-02 2.96775390e-01 6.46745339e-01
 6.18786457e-01 3.74062720e-01]
Mean of the random array: 0.4546


#### Task 5: Create a 10X10 array with random values and find the minimum and maximum values.

In [82]:
import numpy as np

# 5. Create a 10X10 array with random values and find the minimum and maximum values
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\n5. 10x10 array with random values:")
print(random_matrix)
print(f"Minimum value in the array: {min_value:.4f}")
print(f"Maximum value in the array: {max_value:.4f}")


5. 10x10 array with random values:
[[0.42929255 0.18789782 0.99406661 0.26416555 0.81320013 0.12737024
  0.45115622 0.5727844  0.67781847 0.93329117]
 [0.35002388 0.43719512 0.99719652 0.99523845 0.13810716 0.8458304
  0.70210845 0.96241188 0.90799254 0.77588628]
 [0.7715781  0.02868047 0.23892092 0.0509679  0.96804875 0.82216069
  0.43348426 0.784174   0.49848515 0.20451462]
 [0.26541896 0.94284374 0.73145195 0.78224527 0.97965457 0.89684064
  0.10124029 0.71209858 0.55494182 0.8287798 ]
 [0.94653197 0.8909844  0.84952812 0.27280358 0.12459792 0.23055999
  0.93825787 0.95543389 0.97956567 0.97344899]
 [0.6306913  0.37188241 0.9446643  0.71947251 0.32442288 0.85303678
  0.97501271 0.1858672  0.22474604 0.13023694]
 [0.5250845  0.65614523 0.77104815 0.87984564 0.71911321 0.25405589
  0.82926987 0.36028651 0.0815856  0.26837364]
 [0.92120719 0.54528554 0.26343599 0.48066934 0.2648611  0.97184208
  0.49135936 0.6410333  0.69262654 0.03795147]
 [0.99228823 0.09372293 0.96060009 0.37218839

#### Task 6: Create a zero array of size 10 and replace 5th element with 1.

In [83]:
import numpy as np

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
# In Python/NumPy, indexing is 0-based, so the 5th element is at index 4
zero_array[4] = 1
print("\n6. Zero array of size 10 with 5th element replaced by 1:")
print(zero_array)


6. Zero array of size 10 with 5th element replaced by 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Task 7: Reverse an array `arr = [1,2,0,0,4,0]`.

In [84]:
import numpy as np

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Original array:")
print(arr)
print("Reversed array:")
print(reversed_arr)


7. Original array:
[1 2 0 0 4 0]
Reversed array:
[0 4 0 0 2 1]


#### Task 8: Create a 2d array with 1 on border and 0 inside.

In [85]:
import numpy as np

# 8. Create a 2d array with 1 on border and 0 inside
# Let's create a 5x5 array for demonstration
size = 5
board = np.ones((size, size)) # Start with all ones
board[1:-1, 1:-1] = 0 # Set the inner part to zeros

print("\n8. 2D array with 1 on border and 0 inside:")
print(board)

# Another example for a larger array
size_large = 7
board_large = np.ones((size_large, size_large))
board_large[1:-1, 1:-1] = 0
print("\n8. Larger 2D array with 1 on border and 0 inside (7x7):")
print(board_large)


8. 2D array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8. Larger 2D array with 1 on border and 0 inside (7x7):
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### Task 9: Create a 8X8 matrix and fill it with a checkerboard pattern.

In [86]:
import numpy as np

# 9. Create an 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1 # Set every other row, starting from the second, and every other column, starting from the first, to 1
checkerboard[::2, 1::2] = 1 # Set every other row, starting from the first, and every other column, starting from the second, to 1

print("\n9. 8x8 Checkerboard pattern matrix:")
print(checkerboard)


9. 8x8 Checkerboard pattern matrix:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem - 3: Array Operations

In [87]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Initial arrays for Problem 3:")
print(f"x:\n{x}")
print(f"y:\n{y}")
print(f"v: {v}")
print(f"w: {w}")

Initial arrays for Problem 3:
x:
[[1 2]
 [3 5]]
y:
[[5 6]
 [7 8]]
v: [ 9 10]
w: [11 12]


#### Task 1: Add the two array.

In [88]:
# 1. Add the two arrays (x and y)
sum_arrays = x + y
print(f"\n1. Sum of x and y:\n{sum_arrays}")


1. Sum of x and y:
[[ 6  8]
 [10 13]]


#### Task 2: Subtract the two array.

In [89]:
# 2. Subtract the two arrays (x and y)
subtract_arrays = x - y
print(f"\n2. Subtraction of x and y:\n{subtract_arrays}")


2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]


#### Task 3: Multiply the array with any integers of your choice.

In [90]:
# 3. Multiply the array (x) with an integer (e.g., 5)
multiplied_array = x * 5
print(f"\n3. Array x multiplied by 5:\n{multiplied_array}")

# Multiply another array (v) with a different integer (e.g., 2)
multiplied_vector = v * 2
print(f"\n   Vector v multiplied by 2:\n{multiplied_vector}")


3. Array x multiplied by 5:
[[ 5 10]
 [15 25]]

   Vector v multiplied by 2:
[18 20]


#### Task 4: Find the square of each element of the array.

In [91]:
# 4. Find the square of each element of array x
square_x = x ** 2
print(f"\n4. Square of each element in x:\n{square_x}")

# Find the square of each element of array v
square_v = v ** 2
print(f"\n   Square of each element in v:\n{square_v}")


4. Square of each element in x:
[[ 1  4]
 [ 9 25]]

   Square of each element in v:
[ 81 100]


#### Task 5: Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [92]:
# 5. Find the dot product between:

# v and w (vector-vector dot product)
dot_vw = np.dot(v, w)
print(f"\n5. Dot product of v and w: {dot_vw}")

# x and v (matrix-vector dot product)
dot_xv = np.dot(x, v)
print(f"\n   Dot product of x and v:\n{dot_xv}")

# x and y (matrix-matrix dot product)
dot_xy = np.dot(x, y)
print(f"\n   Dot product of x and y:\n{dot_xy}")


5. Dot product of v and w: 219

   Dot product of x and v:
[29 77]

   Dot product of x and y:
[[19 22]
 [50 58]]


#### Task 6: Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

In [93]:
# 6. Concatenate x and y along rows
concatenate_xy_rows = np.concatenate((x, y), axis=0)
print(f"\n6. Concatenating x and y along rows:\n{concatenate_xy_rows}")

# Concatenate v and w along columns
# For 1D arrays, np.concatenate with axis=1 requires them to be 2D.
# Reshape v and w to be column vectors first or use np.hstack.
concatenate_vw_cols = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print(f"\n   Concatenating v and w along columns (reshaped to 2D first):\n{concatenate_vw_cols}")

# Alternative for v and w along columns using np.hstack (more direct for 1D arrays)
concatenate_vw_hstack = np.hstack((v.reshape(-1, 1), w.reshape(-1, 1)))
print(f"\n   Concatenating v and w along columns (using np.hstack with reshape):\n{concatenate_vw_hstack}")


6. Concatenating x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

   Concatenating v and w along columns (reshaped to 2D first):
[[ 9 11]
 [10 12]]

   Concatenating v and w along columns (using np.hstack with reshape):
[[ 9 11]
 [10 12]]


#### Task 7: Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [94]:
import numpy as np

# Arrays x and v are already defined in the previous cell
# x = np.array([[1,2],[3,5]])
# v = np.array([9,10])

try:
    # Attempt to concatenate x (2D) and v (1D) directly
    concatenate_xv = np.concatenate((x, v), axis=0)
    print(f"\n7. Concatenating x and v along rows:\n{concatenate_xv}")
except ValueError as e:
    print(f"\n7. Error when concatenating x and v: {e}")


7. Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


When attempting to concatenate `x` (a 2D array of shape (2, 2)) and `v` (a 1D array of shape (2,)) along `axis=0`, a `ValueError` occurs. This is because NumPy's `concatenate` function requires all arrays to have the same number of dimensions when concatenating along a specific axis, and the sizes of the dimensions must match everywhere except on the concatenation axis itself.

-   `x` has 2 dimensions.
-   `v` has 1 dimension.

To concatenate them, `v` would need to be reshaped to a 2D array, for example, `v.reshape(1, -1)` to become `(1, 2)` if concatenating along `axis=0` (stacking rows), or `v.reshape(-1, 1)` to become `(2, 1)` if concatenating along `axis=1` (stacking columns).

For instance, to stack `v` as a row below `x`, you could use:

```python
np.concatenate((x, v.reshape(1, -1)), axis=0)
# Output would be:
# [[ 1  2]
#  [ 3  5]
#  [ 9 10]]
```

This section demonstrated various array operations in NumPy, including:

-   **Element-wise Arithmetic**: Simple addition (`+`), subtraction (`-`), and multiplication (`*`) between arrays or an array and a scalar, performed element by element.
-   **Element-wise Powers**: Using `**` operator to find the square (or any power) of each element.
-   **Dot Product**: Using `np.dot()` for calculating dot products between vectors, matrix-vector products, and matrix-matrix products.
-   **Concatenation**: Using `np.concatenate()` to join arrays along a specified axis (`axis=0` for rows, `axis=1` for columns). It also highlighted the importance of compatible dimensions for successful concatenation.

### Problem - 4: Matrix Operations

### Problem - 4: Matrix Operations

In [95]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

print("Initial arrays for Problem 4:")
print(f"A:\n{A}")
print(f"B:\n{B}")

Initial arrays for Problem 4:
A:
[[3 4]
 [7 8]]
B:
[[5 3]
 [2 1]]


#### Task 1: Prove A.A−1 = I.

In [96]:
# 1. Prove A.A−1 = I

# Calculate the inverse of A
A_inv = np.linalg.inv(A)
print(f"\nInverse of A (A_inv):\n{A_inv}")

# Calculate A . A_inv
product_A_A_inv = np.dot(A, A_inv)
print(f"\nProduct A . A_inv:\n{product_A_A_inv}")

# Create an identity matrix of the same size as A
identity_matrix = np.eye(A.shape[0])
print(f"\nIdentity matrix (I):\n{identity_matrix}")

# Check if A . A_inv is close to the identity matrix (due to floating point precision)
# np.allclose is used for numerical comparisons involving floats
is_identity = np.allclose(product_A_A_inv, identity_matrix)
print(f"\nIs A . A_inv approximately equal to I? {is_identity}")


Inverse of A (A_inv):
[[-2.    1.  ]
 [ 1.75 -0.75]]

Product A . A_inv:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix (I):
[[1. 0.]
 [0. 1.]]

Is A . A_inv approximately equal to I? True


#### Task 2: Prove AB ≠ BA.

In [97]:
# 2. Prove AB ≠ BA

# Calculate AB
product_AB = np.dot(A, B)
print(f"\nProduct AB:\n{product_AB}")

# Calculate BA
product_BA = np.dot(B, A)
print(f"\nProduct BA:\n{product_BA}")

# Check if AB is equal to BA
is_equal_AB_BA = np.array_equal(product_AB, product_BA)
print(f"\nIs AB equal to BA? {is_equal_AB_BA}")
print("This demonstrates that matrix multiplication is generally not commutative.")


Product AB:
[[23 13]
 [51 29]]

Product BA:
[[36 44]
 [13 16]]

Is AB equal to BA? False
This demonstrates that matrix multiplication is generally not commutative.


#### Task 3: Prove (AB)T = BTAT

In [98]:
# 3. Prove (AB)T = BTAT

# Calculate AB
product_AB = np.dot(A, B)
print(f"\nProduct AB:\n{product_AB}")

# Calculate (AB)T
AB_transpose = product_AB.T
print(f"\n(AB)T:\n{AB_transpose}")

# Calculate BT
B_transpose = B.T
print(f"\nBT:\n{B_transpose}")

# Calculate AT
A_transpose = A.T
print(f"\nAT:\n{A_transpose}")

# Calculate BTAT
product_B_transpose_A_transpose = np.dot(B_transpose, A_transpose)
print(f"\nBTAT:\n{product_B_transpose_A_transpose}")

# Check if (AB)T is approximately equal to BTAT
is_equal_transpose_product = np.allclose(AB_transpose, product_B_transpose_A_transpose)
print(f"\nIs (AB)T approximately equal to BTAT? {is_equal_transpose_product}")


Product AB:
[[23 13]
 [51 29]]

(AB)T:
[[23 51]
 [13 29]]

BT:
[[5 2]
 [3 1]]

AT:
[[3 7]
 [4 8]]

BTAT:
[[23 51]
 [13 29]]

Is (AB)T approximately equal to BTAT? True


#### Solve the following system of Linear equation using Inverse Methods.

$2x - 3y + z = -1$
$x - y + 2z = -3$
$3x + y - z = 9$

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [99]:
import numpy as np

# Represent the system of linear equations in matrix form AX = B
# A is the coefficient matrix
A_system = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

# B is the constants matrix (right-hand side)
B_system = np.array([-1, -3, 9])

print(f"\nCoefficient Matrix A_system:\n{A_system}")
print(f"Constants Matrix B_system: {B_system}")

# Solve for X using the inverse method: X = A_inv * B
# First, calculate the inverse of A_system
A_system_inv = np.linalg.inv(A_system)
print(f"\nInverse of A_system:\n{A_system_inv}")

# Then, multiply A_system_inv by B_system to find the solution vector X
X_solution = np.dot(A_system_inv, B_system)

print(f"\nSolution for x, y, z (X_solution): {X_solution}")

# Verify the solution by plugging X_solution back into the original equations (A_system @ X_solution)
verification = np.dot(A_system, X_solution)
print(f"\nVerification (A_system @ X_solution): {verification}")
print(f"Is verification close to B_system? {np.allclose(verification, B_system)}")


Coefficient Matrix A_system:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants Matrix B_system: [-1 -3  9]

Inverse of A_system:
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution for x, y, z (X_solution): [ 2.  1. -2.]

Verification (A_system @ X_solution): [-1. -3.  9.]
Is verification close to B_system? True


## 10.2 Experiment: How Fast is Numpy?

### 1. Element-wise Addition

In [100]:
import numpy as np
import time

SIZE = 1_000_000 # Size of the lists/arrays

# Python Lists - Element-wise Addition
list1 = list(range(SIZE))
list2 = list(range(SIZE))

start_time = time.perf_counter()
result_list = [list1[i] + list2[i] for i in range(SIZE)]
end_time = time.perf_counter()
python_list_time = (end_time - start_time) * 1000 # Convert to milliseconds
print(f"Python Lists - Element-wise Addition: {python_list_time:.4f} ms")

# NumPy Arrays - Element-wise Addition
array1 = np.arange(SIZE)
array2 = np.arange(SIZE)

start_time = time.perf_counter()
result_array = array1 + array2
end_time = time.perf_counter()
numpy_array_time = (end_time - start_time) * 1000 # Convert to milliseconds
print(f"NumPy Arrays - Element-wise Addition: {numpy_array_time:.4f} ms")

print(f"NumPy is approximately {python_list_time / numpy_array_time:.2f} times faster for element-wise addition.")

Python Lists - Element-wise Addition: 116.6425 ms
NumPy Arrays - Element-wise Addition: 4.7327 ms
NumPy is approximately 24.65 times faster for element-wise addition.


### 2. Element-wise Multiplication

In [101]:
import numpy as np
import time

SIZE = 1_000_000 # Size of the lists/arrays

# Python Lists - Element-wise Multiplication
list1_mult = [i for i in range(SIZE)]
list2_mult = [i for i in range(SIZE)]

start_time_py = time.perf_counter()
result_list_mult = [list1_mult[i] * list2_mult[i] for i in range(SIZE)]
end_time_py = time.perf_counter()
python_list_time_mult = (end_time_py - start_time_py) * 1000 # Convert to milliseconds
print(f"Python Lists - Element-wise Multiplication: {python_list_time_mult:.4f} ms")

# NumPy Arrays - Element-wise Multiplication
array1_mult = np.arange(SIZE)
array2_mult = np.arange(SIZE)

start_time_np = time.perf_counter()
result_array_mult = array1_mult * array2_mult
end_time_np = time.perf_counter()
numpy_array_time_mult = (end_time_np - start_time_np) * 1000 # Convert to milliseconds
print(f"NumPy Arrays - Element-wise Multiplication: {numpy_array_time_mult:.4f} ms")

print(f"NumPy is approximately {python_list_time_mult / numpy_array_time_mult:.2f} times faster for element-wise multiplication.")

Python Lists - Element-wise Multiplication: 110.7734 ms
NumPy Arrays - Element-wise Multiplication: 4.5161 ms
NumPy is approximately 24.53 times faster for element-wise multiplication.


### 3. Dot Product

In [102]:
import numpy as np
import time

SIZE = 1_000_000 # Size of the lists/arrays

# Python Lists - Dot Product
list1_dot = [i for i in range(SIZE)]
list2_dot = [i for i in range(SIZE)]

start_time_py_dot = time.perf_counter()
dot_product_py = sum(list1_dot[i] * list2_dot[i] for i in range(SIZE))
end_time_py_dot = time.perf_counter()
python_list_time_dot = (end_time_py_dot - start_time_py_dot) * 1000 # Convert to milliseconds
print(f"Python Lists - Dot Product: {python_list_time_dot:.4f} ms")

# NumPy Arrays - Dot Product
array1_dot = np.arange(SIZE)
array2_dot = np.arange(SIZE)

start_time_np_dot = time.perf_counter()
dot_product_np = np.dot(array1_dot, array2_dot)
end_time_np_dot = time.perf_counter()
numpy_array_time_dot = (end_time_np_dot - start_time_np_dot) * 1000 # Convert to milliseconds
print(f"NumPy Arrays - Dot Product: {numpy_array_time_dot:.4f} ms")

print(f"NumPy is approximately {python_list_time_dot / numpy_array_time_dot:.2f} times faster for dot product.")

Python Lists - Dot Product: 102.0439 ms
NumPy Arrays - Dot Product: 1.8687 ms
NumPy is approximately 54.61 times faster for dot product.


### 4. Matrix Multiplication

In [54]:
import numpy as np
import time

MATRIX_SIZE = 500 # Size of the square matrices (e.g., 500x500)

# Python Lists - Matrix Multiplication (Naive implementation)
def multiply_matrices_py(matrix_a, matrix_b):
    rows_a = len(matrix_a)
    cols_a = len(matrix_a[0])
    rows_b = len(matrix_b)
    cols_b = len(matrix_b[0])

    if cols_a != rows_b:
        raise ValueError("Matrices have incompatible dimensions for multiplication.")

    result_matrix = [[0 for _ in range(cols_b)] for _ in range(rows_a)]

    for i in range(rows_a):
        for j in range(cols_b):
            for k in range(cols_a):
                result_matrix[i][j] += matrix_a[i][k] * matrix_b[k][j]
    return result_matrix

# Create Python lists representing matrices
matrix_a_py = [[(i * MATRIX_SIZE + j) % 10 for j in range(MATRIX_SIZE)] for i in range(MATRIX_SIZE)]
matrix_b_py = [[(i * MATRIX_SIZE + j) % 10 for j in range(MATRIX_SIZE)] for i in range(MATRIX_SIZE)]

print(f"Performing matrix multiplication for {MATRIX_SIZE}x{MATRIX_SIZE} matrices...")

start_time_py_matrix = time.perf_counter()
result_matrix_py = multiply_matrices_py(matrix_a_py, matrix_b_py)
end_time_py_matrix = time.perf_counter()
python_list_time_matrix = (end_time_py_matrix - start_time_py_matrix) * 1000 # Convert to milliseconds
print(f"Python Lists - Matrix Multiplication: {python_list_time_matrix:.4f} ms")

# NumPy Arrays - Matrix Multiplication
matrix_a_np = np.random.randint(0, 10, size=(MATRIX_SIZE, MATRIX_SIZE))
matrix_b_np = np.random.randint(0, 10, size=(MATRIX_SIZE, MATRIX_SIZE))

start_time_np_matrix = time.perf_counter()
result_matrix_np = np.dot(matrix_a_np, matrix_b_np)
end_time_np_matrix = time.perf_counter()
numpy_array_time_matrix = (end_time_np_matrix - start_time_np_matrix) * 1000 # Convert to milliseconds
print(f"NumPy Arrays - Matrix Multiplication: {numpy_array_time_matrix:.4f} ms")

print(f"NumPy is approximately {python_list_time_matrix / numpy_array_time_matrix:.2f} times faster for matrix multiplication.")

Performing matrix multiplication for 500x500 matrices...
Python Lists - Matrix Multiplication: 15197.2151 ms
NumPy Arrays - Matrix Multiplication: 167.0331 ms
NumPy is approximately 90.98 times faster for matrix multiplication.
